#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
LIGHT_BLUE='\033[1;34m'
NO_COLOR='\033[0m'


echo "${LIGHT_BLUE}!${NO_COLOR} Checking Lint"
bun run lint || exit $
echo "${GREEN}✔${NO_COLOR} Done Running Lint"

echo "${LIGHT_BLUE}!${NO_COLOR} Formatting Staged Files"
bunx biome check --staged --no-errors-on-unmatched

echo "${GREEN} Formatted" ${staged}
echo "${GREEN}✔${NO_COLOR} Done Formatting"

echo "${LIGHT_BLUE}!${NO_COLOR} Checking for Circlar Dependency"
bun run cruise || exit $

echo "${GREEN}✔${NO_COLOR} Done Running Pre-commit\n"